# Generated by Django 5.1.4 on 2024-12-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket_authentication', '0002_alter_basketinfomodel_customer_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketinfomodel',
            name='customer_company_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketinfomodel',
            name='goods_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
